{
 "title": "Triton Inference Server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GPU utilization gauge",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_gpu_utilization" }
   ]
  },
  {
   "title": "GPU utilization [0.0 - 1.0)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nv_gpu_utilization", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GPU power usage (in Watts)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nv_gpu_power_usage", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Request duration (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nv_inference_request_duration_us[30s]) / 1000 ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queue time (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us[30s]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inference compute duration (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nv_inference_compute_infer_duration_us[30s]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of model executions performed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nv_inference_exec_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Number of inferences performed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nv_inference_request_success", "legendFormat": "Success {{instance}}" }
   ]
  }
 ]
}